/**
 * Automatic capture on Claude Code hooks: what compaction mines from the
 * transcript, which failed tool calls become error memories, and that both
 * install routes (`hippo init`, `hippo hook install claude-code`) wire the
 * same hooks. Found by running a real Claude Code `/compact` against
 * hippo's hooks (2026-09-24): the compaction mined Claude Code's own
 * boilerplate and missed the user's decision.
 * Real CLI, real stores, real settings files. No mocks.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { spawnSync } from 'node:child_process';
import { extractFromText, preCompactMessage, postCompactMessage, preCompactReportPath } from '../src/capture.js';
import { lessonFromFailure, captureToolFailure, failureSignature } from '../src/capture-error.js';
import { initStore, loadAllEntries, getHippoRoot } from '../src/store.js';
import { installJsonHooks } from '../src/hooks.js';
import { runDoctor } from '../src/doctor.js';

const HIPPO_JS = path.resolve(__dirname, '..', 'bin', 'hippo.js');

/** A scratch directory and a child environment rooted in it. */
interface Scratch {
  dir: string;
  env: NodeJS.ProcessEnv;
}

function scratch(): Scratch {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hippo-auto-capture-'));
  const env: NodeJS.ProcessEnv = { ...process.env, HIPPO_HOME: path.join(dir, 'global'), HOME: dir, USERPROFILE: dir };
  delete env.CLAUDE_CODE_SESSION_ID;
  delete env.HIPPO_SESSION_ID;
  return { dir, env };
}
function run(args: string[], cwd: string, env: NodeJS.ProcessEnv, input?: string) {
  return spawnSync(process.execPath, [HIPPO_JS, ...args], { cwd, env, input, encoding: 'utf8' });
}

describe('transcript mining', () => {
  it('documents a known miss: a comma-split decision is too thin to keep (heuristics, no model)', () => {
    // Found in the real /compact run on 2026-09-24. Clause bounding cuts this
    // sentence at its commas, and both halves fall under the quality floor.
    // LLM extraction (config `extraction`) or better bounding is the fix;
    // this test fails when that lands, as a reminder to update it.
    expect(extractFromText('Decision: we use pnpm, never npm, because the lockfile is pnpm-lock.yaml.')).toEqual([]);
  });

  it('pre-compact skips Claude Code compact summaries and slash-command lines', () => {
    const { dir, env } = scratch();
    try {
      expect(run(['init', '--no-hooks', '--no-schedule', '--no-learn'], dir, env).status).toBe(0);
      const transcript = path.join(dir, 't.jsonl');
      const lines = [
        { type: 'user', message: { role: 'user', content: 'Never run npm install in the billing service; the lockfile is pnpm-lock.yaml.' } },
        { type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: 'OK.' }] } },
        { type: 'user', isCompactSummary: true, message: { role: 'user', content: 'This session is being continued from a previous conversation. Always restart the server after deploys.' } },
        { type: 'user', isMeta: true, message: { role: 'user', content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>' } },
        { type: 'user', message: { role: 'user', content: '<command-name>/compact</command-name>' } },
        { type: 'user', message: { role: 'user', content: '<local-command-stdout>Compacted. Never mind this output.</local-command-stdout>' } },
      ];
      fs.writeFileSync(transcript, lines.map((l) => JSON.stringify(l)).join('\n') + '\n');
      const payload = JSON.stringify({ session_id: 's1', transcript_path: transcript, cwd: dir, hook_event_name: 'PreCompact', trigger: 'manual' });
      expect(run(['pre-compact'], dir, env, payload).status).toBe(0);
      const contents = loadAllEntries(getHippoRoot(dir), 'default').map((e) => e.content).join(' | ');
      expect(contents).toMatch(/npm install/);
      expect(contents).not.toMatch(/restart the server|local commands|Never mind this output/i);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('after compaction the user is told what hippo saved, once, and pre-compact prints nothing', () => {
    // Claude Code passes PreCompact stdout to the summarising model as
    // instructions, so the message comes from the PostCompact hook instead.
    expect(preCompactMessage({ snapshotSaved: false, captured: 0 })).toBeNull();
    expect(preCompactMessage({ snapshotSaved: false, captured: 1 })).toBe('Hippo saved 1 new memory before compacting.');
    expect(preCompactMessage({ snapshotSaved: true, captured: 3 })).toBe(
      'Hippo saved your task snapshot and 3 new memories before compacting. The snapshot is restored into the new context.',
    );

    const { dir, env } = scratch();
    try {
      expect(run(['init', '--no-hooks', '--no-schedule', '--no-learn'], dir, env).status).toBe(0);
      const logFile = path.join(dir, 'logs', 'pre-compact.log');
      const transcript = path.join(dir, 't.jsonl');
      const lines = [
        { type: 'user', message: { role: 'user', content: 'Fix the flaky login test. Never run npm install in the billing service; the lockfile is pnpm-lock.yaml.' } },
        { type: 'assistant', message: { role: 'assistant', content: [{ type: 'text', text: 'Looking at the login test now.' }] } },
      ];
      fs.writeFileSync(transcript, lines.map((l) => JSON.stringify(l)).join('\n') + '\n');
      const compact = (session: string) => run(['pre-compact', '--log-file', logFile], dir, env,
        JSON.stringify({ session_id: session, transcript_path: transcript, cwd: dir, hook_event_name: 'PreCompact', trigger: 'auto' }));
      const post = (session: string) => run(['post-compact', '--log-file', logFile], dir, env,
        JSON.stringify({ session_id: session, cwd: dir, hook_event_name: 'PostCompact', trigger: 'auto' }));

      const pre = compact('s1');
      expect(pre.status).toBe(0);
      expect(pre.stdout).toBe('');
      const shown = post('s1');
      expect(shown.status).toBe(0);
      expect(shown.stdout.trim()).toMatch(/^Hippo saved your task snapshot( and \d+ new memor(y|ies))? before compacting\. The snapshot is restored/);
      expect(post('s1').stdout).toBe('');

      // Another session's report is not shown.
      expect(compact('s1').status).toBe(0);
      expect(post('s2').stdout).toBe('');
      // Nothing saved, nothing said.
      expect(run(['post-compact', '--log-file', path.join(dir, 'none', 'x.log')], dir, env, '').stdout).toBe('');
      expect(postCompactMessage(undefined, path.join(dir, 'none', 'x.log'))).toBeNull();
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('a project without its own store compacts into the global store, and resumes from it', () => {
    const { dir, env } = scratch();
    try {
      const proj = path.join(dir, 'proj');
      fs.mkdirSync(proj);
      expect(run(['init', '--global', '--no-hooks', '--no-schedule', '--no-learn'], proj, env).status).toBe(0);
      const transcript = path.join(proj, 't.jsonl');
      fs.writeFileSync(transcript, JSON.stringify({ type: 'user', message: { role: 'user', content: 'Fix the flaky login test in the billing service.' } }) + '\n');
      const pre = run(['pre-compact', '--log-file', path.join(dir, 'logs', 'pc.log')], proj, env,
        JSON.stringify({ session_id: 's1', transcript_path: transcript, cwd: proj, hook_event_name: 'PreCompact', trigger: 'manual' }));
      expect(pre.status).toBe(0);
      expect(fs.existsSync(path.join(proj, '.hippo'))).toBe(false);
      const resume = run(['compact-resume'], proj, env, JSON.stringify({ session_id: 's1', source: 'compact', cwd: proj }));
      expect(resume.stdout).toContain('Fix the flaky login test');
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('with no store anywhere, the compaction hooks create nothing', () => {
    const { dir, env } = scratch();
    try {
      const transcript = path.join(dir, 't.jsonl');
      fs.writeFileSync(transcript, JSON.stringify({ type: 'user', message: { role: 'user', content: 'Fix the flaky login test.' } }) + '\n');
      expect(run(['pre-compact', '--log-file', path.join(dir, 'logs', 'pc.log')], dir, env,
        JSON.stringify({ session_id: 's1', transcript_path: transcript, cwd: dir })).status).toBe(0);
      expect(run(['compact-resume'], dir, env, JSON.stringify({ session_id: 's1', source: 'compact' })).status).toBe(0);
      expect(fs.existsSync(path.join(dir, '.hippo'))).toBe(false);
      expect(fs.existsSync(path.join(dir, 'global'))).toBe(false);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('a stale pre-compact report is not shown', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hippo-post-compact-'));
    try {
      const logFile = path.join(dir, 'pre-compact.log');
      const write = (at: string) => fs.writeFileSync(preCompactReportPath(logFile), JSON.stringify({ snapshotSaved: true, captured: 0, sessionId: null, at }));
      write('2026-09-24T10:00:00.000Z');
      expect(postCompactMessage('{}', logFile, new Date('2026-09-24T11:00:00.000Z'))).toBeNull();
      write('2026-09-24T10:00:00.000Z');
      expect(postCompactMessage('{}', logFile, new Date('2026-09-24T10:01:00.000Z'))).toMatch(/^Hippo saved your task snapshot/);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('failed-tool capture', () => {
  it('skips routine failures and keeps real errors', () => {
    const unread = (skip: string) => ({ skip, text: null, detail: null });
    expect(lessonFromFailure({ tool_name: 'Bash', error: 'Interrupted by user', is_interrupt: true })).toEqual(unread('skipped-interrupt'));
    const declined = "Edit: The user doesn't want to proceed with this tool use.";
    expect(lessonFromFailure({ tool_name: 'Edit', error: "The user doesn't want to proceed with this tool use." }))
      .toEqual({ skip: 'skipped-routine', rule: 'declined', text: declined, detail: declined });
    expect(lessonFromFailure({ tool_name: 'Grep', error: 'No matches found for pattern foo' }))
      .toMatchObject({ skip: 'skipped-routine', rule: 'no-match', text: 'Grep: No matches found for pattern foo' });
    expect(lessonFromFailure({ tool_name: 'Glob', error: 'Invalid glob pattern: src/[abc' })).toMatchObject({ rule: 'search-tool' });
    expect(lessonFromFailure({ tool_name: 'Bash', tool_input: { command: 'grep -r TODO src' }, error: 'Exit code 1 (no output)' }))
      .toEqual({ skip: 'skipped-routine', rule: 'quiet-exit', text: 'Bash: Exit code 1 (no output)', detail: 'Bash grep -r: Exit code 1 (no output)' });
    expect(lessonFromFailure('not an object')).toEqual(unread('skipped-invalid'));
    expect(lessonFromFailure({ tool_name: 'Bash', error: 'short' })).toEqual(unread('skipped-invalid'));
    const real = lessonFromFailure({ tool_name: 'Bash', tool_input: { command: 'npm test' }, error: "Exit code 1\nError: Cannot find module 'express'" });
    expect(real).toEqual({
      text: "Bash: Exit code 1 Error: Cannot find module 'express'",
      detail: "Bash npm test: Exit code 1 Error: Cannot find module 'express'",
    });
  });

  it('reads a command past any leading cd, and tells OS permission errors from declines', () => {
    const bash = (command: string, error: string) => lessonFromFailure({ tool_name: 'Bash', tool_input: { command }, error });
    const broke = 'Exit code 1 Error: Cannot find module express';
    expect(bash('cd /repo && npm test', broke)).toMatchObject({ detail: `Bash npm test: ${broke}` });
    expect(bash('cd /repo; cd sub && npm run build', broke)).toMatchObject({ detail: `Bash npm run: ${broke}` });
    expect(bash('cd /missing', 'cd: /missing: No such file or directory'))
      .toEqual({ text: 'Bash: cd: /missing: No such file or directory', detail: 'Bash cd /missing: cd: /missing: No such file or directory' });
    expect(bash('cd /repo && grep -r TODO src', 'Exit code 1 (no output)')).toMatchObject({ skip: 'skipped-routine', rule: 'quiet-exit' });
    expect(bash('git push', 'git@github.com: Permission denied (publickey).')).toMatchObject({ skip: 'skipped-routine', rule: 'os-permission' });
    expect(lessonFromFailure({ tool_name: 'Read', error: "EACCES: permission denied, open '/srv/app/config.json'" })).toMatchObject({ rule: 'os-permission' });
    expect(lessonFromFailure({ tool_name: 'Bash', error: 'Permission to use Bash has been denied.' })).toMatchObject({ rule: 'declined' });
  });

  it('stores an unverified error memory once, however often it repeats', () => {
    const { dir } = scratch();
    try {
      initStore(dir);
      const payload = { tool_name: 'Bash', tool_input: { command: 'npm run build' }, error: 'Exit code 2\nsrc/a.ts(12,3): error TS2304: Cannot find name foo' };
      expect(captureToolFailure(dir, 'default', payload)).toBe('stored');
      expect(captureToolFailure(dir, 'default', { ...payload, error: 'Exit code 2\nsrc/a.ts(40,9): error TS2304: Cannot find name foo' })).toBe('duplicate');
      const rows = loadAllEntries(dir, 'default');
      expect(rows).toHaveLength(1);
      expect(rows[0]!.tags).toEqual(expect.arrayContaining(['error', 'auto-captured']));
      expect(rows[0]!.confidence).toBe('observed');
      expect(failureSignature('line 12 at 0xdeadbeef')).toBe(failureSignature('line 40 at 0x1234567'));
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('the hook command never creates a store and always exits 0', () => {
    const { dir, env } = scratch();
    try {
      const r = run(['capture-error'], dir, env, JSON.stringify({ tool_name: 'Bash', error: 'Exit code 1\nError: something real broke here' }));
      expect(r.status).toBe(0);
      expect(fs.existsSync(path.join(dir, '.hippo'))).toBe(false);
      expect(fs.existsSync(path.join(dir, 'global'))).toBe(false);
      expect(run(['capture-error'], dir, env, 'garbage').status).toBe(0);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('both install routes wire compaction and failed-tool capture', () => {
  let dir: string;
  let saved: Pick<NodeJS.ProcessEnv, 'HOME' | 'USERPROFILE'>;
  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hippo-install-parity-'));
    saved = { HOME: process.env.HOME, USERPROFILE: process.env.USERPROFILE };
    process.env.HOME = dir;
    process.env.USERPROFILE = dir;
  });
  afterEach(() => {
    for (const [k, v] of Object.entries(saved)) {
      if (v === undefined) delete process.env[k];
      else process.env[k] = v;
    }
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it('hippo hook install adds PreCompact and PostToolUseFailure, idempotently', () => {
    const first = installJsonHooks('claude-code');
    expect(first.installedPreCompact).toBe(true);
    expect(first.installedCaptureError).toBe(true);
    expect(first.installedPostCompact).toBe(true);
    expect(installJsonHooks('claude-code').installedCaptureError).toBe(false);
    const settings = fs.readFileSync(path.join(dir, '.claude', 'settings.json'), 'utf8');
    expect(settings).toContain('hippo pre-compact');
    expect(settings).toContain('hippo capture-error');
    expect(settings).toContain('hippo post-compact');
  });

  it('re-running hippo init adds hooks a newer hippo introduced even when CLAUDE.md already has the block', () => {
    const env: NodeJS.ProcessEnv = { ...process.env, HOME: dir, USERPROFILE: dir, HIPPO_HOME: path.join(dir, 'global') };
    const proj = path.join(dir, 'proj');
    fs.mkdirSync(proj);
    fs.writeFileSync(path.join(proj, 'CLAUDE.md'), '# Project\n');
    expect(run(['init', '--no-schedule', '--no-learn'], proj, env).status).toBe(0);
    // Simulate an install from before PreCompact and PostToolUseFailure existed.
    const settingsPath = path.join(dir, '.claude', 'settings.json');
    const settings = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    delete settings.hooks.PreCompact;
    delete settings.hooks.PostToolUseFailure;
    delete settings.hooks.PostCompact;
    fs.writeFileSync(settingsPath, JSON.stringify(settings));
    expect(fs.readFileSync(path.join(proj, 'CLAUDE.md'), 'utf8')).toContain('hippo');

    const again = run(['init', '--no-schedule', '--no-learn'], proj, env);
    expect(again.status).toBe(0);
    const after = fs.readFileSync(settingsPath, 'utf8');
    expect(after).toContain('hippo pre-compact');
    expect(after).toContain('hippo capture-error');
    expect(after).toContain('hippo post-compact');
  });

  it('hippo doctor names the missing hooks', () => {
    initStore(path.join(dir, '.hippo'));
    fs.mkdirSync(path.join(dir, '.claude'), { recursive: true });
    fs.writeFileSync(path.join(dir, '.claude', 'settings.json'), JSON.stringify({ hooks: {
      UserPromptSubmit: [{ hooks: [{ type: 'command', command: 'hippo context --pinned-only' }] }],
      SessionEnd: [{ hooks: [{ type: 'command', command: 'hippo session-end' }] }],
    } }));
    const check = runDoctor({ cwd: dir, home: dir, version: 't' }).checks.find((c) => c.id === 'claude-code')!;
    expect(check.status).toBe('warn');
    expect(check.detail).toMatch(/compaction snapshot and capture/);
    expect(check.detail).toMatch(/failed-tool capture/);
    installJsonHooks('claude-code');
    expect(runDoctor({ cwd: dir, home: dir, version: 't' }).checks.find((c) => c.id === 'claude-code')!.status).toBe('pass');
  });
});
